### PR TITLE
Multiple location fields on the same page.

### PR DESCRIPTION
**Pull request by edgaru**
To add multiple maps its necessary to specify the id in map_attrs of each field. #13 

Example: 
```
starting_location = LocationField(map_attrs={"id": "starting_location"})
destination_location = LocationField(map_attrs={"id": "destination_location"})
```

### CODE REVIEW

**Comment by Simon-the-Shark** [comment]
Hi! Nice work, but unfortunately your solution is not complete. It is totally missing AutoHiddenAddressField implementation and always the last map overrides the other's map_attrs. Nevertheless, your code has done the job partially, so I'm merging it to a separate branch and I'll be working on a full solution in the next few days.

**Comment by Simon-the-Shark** [comment]
Thank's for your contribution. I will let you know, once it's done and available on PyPi.

**Comment by Simon-the-Shark** [comment]
Next time also change (or add) some tests

**Comment by edgaru** [comment]
I'll do it better next time, thank you.

**Pull request merged**
