### PR TITLE
Uncaught ReferenceError: map_attr_style is not define.

### PR DESCRIPTION
**Pull request by edgaru**
Is it the correct way to access to map attributes?

### CODE REVIEW

**Comment by Simon-the-Shark** [comment]
Yes, map_attrs[id].some_attribute is the current way how I access the map's attributes. Of course, these attributes are defined before in map_input.html file.

**Comment by Simon-the-Shark** [comment]
However, I don't see the point of this pull request. Asking questions should rather take place in the issues section. Pull requests are preferably for some changes that you want to contribute to my repository.

**Comment by Simon-the-Shark** [comment]
If I were you and wanted to catch up with changes in my repository, I would merge this repository's master branch into your fork. That's how your forked repository would be up-to-date. So basically, I don't the purpose of your commit (05c7ba0). It does not contribute anything, so I just close this PR. You can reopen it if I didn't get your intent correctly.

**Comment by h3x4git** [comment]
I have this same issue when upgrading this package via pip from version 1.5.0 to 2.0.0 on Django 3.2, only on production though. So I have to stick to 1.5.0, while I can't replicate the problem locally with Django's development server. The maps shows correctly there

**Pull request closed without merging**
